name: futebol_tv
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  intl: 0.17.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  mocktail: ^0.3.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.3
  go_router: 5.0.0
  flutter_native_splash: ^2.2.16
  cupertino_icons: ^1.0.2
  page_view_indicators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.1.11
  injectable_generator: 1.5.3
  http_mock_adapter: ^0.3.3

flutter_native_splash:
  color: "#071b5d"
  image: assets/icons/logo.png
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/


